name: Build a Docker image and Push it to ACR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_ENDPOINT }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - run: |
          chmod +x gradlew
          ./gradlew -Pprod bootJar jibDockerBuild
          docker tag libraary ${{ secrets.ACR_ENDPOINT }}/libraary:v0.0.1.0.0
          docker push ${{ secrets.ACR_ENDPOINT }}/libraary:v0.0.1.0.0
